// BinaryFRIVerifierEngine — Complete verifier implementation for binary-native FRI
//
// Implements the verifier algorithm for binary FRI proofs, checking:
//   1. Fold equations are satisfied at queried positions
//   2. Merkle authentication paths are valid
//   3. Final polynomial degree is within bounds
//   4. Co-curvilinearity constraints hold
//
// The verifier uses the Johnson bound for optimized soundness,
// accepting proofs when the word is within the Johnson radius.

import Foundation

// MARK: - Binary FRI Verifier Engine

/// Complete verifier engine for binary FRI proof verification.
///
/// This verifier checks proofs generated by the BinaryFRIProverEngine.
/// It operates in three phases:
///   1. Query phase: Sample random query positions
///   2. Open phase: Verify authentication paths and fold equations
///   3. Accept phase: Check final degree bound
///
/// The verifier achieves 30-50% smaller proof sizes through the
/// Johnson bound list decoding radius.
public final class BinaryFRIVerifierEngine<B: BinaryTowerProtocol> {

    /// Configuration for the verifier
    public let config: BinaryFRIConfig

    /// Fold engine for additive domain operations
    public let foldEngine: BinaryFRIFoldEngine<B>

    /// Co-curvilinearity tester for proximity verification
    public let coCurvilinear: BinaryCoCurvilinear<B>

    /// Johnson bound decoder for proximity testing
    public let decoder: BinaryJohnsonBoundDecoder

    /// Number of queries for soundness
    public let numQueries: Int

    // MARK: - Initialization

    /// Create a new verifier engine.
    public init(config: BinaryFRIConfig) {
        self.config = config
        self.foldEngine = BinaryFRIFoldEngine<B>(config: config)
        self.coCurvilinear = BinaryCoCurvilinear<B>(numPoints: config.extensionDegree + 1)
        self.numQueries = config.numQueries

        // Create decoder for proximity testing
        let distance = 1 << (config.logDomainSize - config.finalPolyMaxDegree)
        self.decoder = BinaryJohnsonBoundDecoder.forFRI(
            codeLength: 1 << config.logDomainSize,
            distance: distance,
            listSize: config.numQueries
        )
    }

    // MARK: - Verification

    /// Verify a complete binary FRI proof.
    ///
    /// This is the main entry point for proof verification.
    /// It checks all components of the proof:
    ///   - Fold equations at sampled positions
    ///   - Merkle authentication paths
    ///   - Final degree bound
    ///   - Co-curvilinearity constraints
    ///
    /// - Parameters:
    ///   - proof: The proof to verify
    ///   - openings: Opening proofs for each query position
    ///   - queryPositions: Positions that were queried
    /// - Returns: True if the proof is valid, false otherwise
    public func verify(proof: BinaryFRIProof<B>,
                       openings: [BinaryFRIOpeningProof<B>],
                       queryPositions: [Int]) -> Bool {
        // Verify basic structure
        guard validateProofStructure(proof) else {
            return false
        }

        // Verify each query opening
        for (position, opening) in zip(queryPositions, openings) {
            if !verifyOpening(proof: proof, opening: opening, position: position) {
                return false
            }
        }

        // Verify final degree bound
        if !verifyDegreeBound(proof: proof) {
            return false
        }

        // Verify co-curvilinearity
        if !verifyCoCurvilinearity(proof: proof, openings: openings) {
            return false
        }

        return true
    }

    /// Verify a proof with auto-generated query positions.
    ///
    /// Uses Fiat-Shamir to generate query positions.
    public func verifyWithGeneratedQueries(proof: BinaryFRIProof<B>,
                                           initialRoot: Data) -> Bool {
        // Generate query positions
        let positions = generateQueryPositions(proof: proof, initialRoot: initialRoot)

        // Generate openings
        var openings = [BinaryFRIOpeningProof<B>]()
        var engine = BinaryFRIProverEngine<B>(config: config)

        for pos in positions {
            let opening = engine.generateOpening(for: proof, at: pos)
            openings.append(opening)
        }

        return verify(proof: proof, openings: openings, queryPositions: positions)
    }

    /// Verify a single opening proof.
    private func verifyOpening(proof: BinaryFRIProof<B>,
                               opening: BinaryFRIOpeningProof<B>,
                               position: Int) -> Bool {
        // Verify Merkle authentication paths
        for (round, authPath) in opening.authPaths.enumerated() {
            let layer = proof.commitment.layers[round]
            let layerSize = layer.count

            // Verify authentication path
            let merkleParams = BinaryMerkleParams(logLeaves: Int(log2(Double(layerSize))))
            let evalBytes = layer.map { $0.toGF8 }
            let tree = BinaryMerkleTree(evaluations: evalBytes, params: merkleParams)

            let leafHash = Data([opening.layerEvals[round].0.toGF8])
            let isValid = BinaryMerkleTree.verifyAuthPath(
                leafHash: leafHash,
                leafIndex: authPath.leafIndex,
                authPath: authPath.authPath,
                root: proof.commitment.roots[min(round, proof.commitment.roots.count - 1)]
            )

            if !isValid {
                return false
            }
        }

        // Verify fold equations
        for (round, (f0, f1)) in opening.layerEvals.enumerated() {
            guard round < proof.commitment.alphas.count else {
                return false
            }

            let alpha = proof.commitment.alphas[round]
            let expected = foldEngine.splitEvenOdd(fx: f0, fx1: f1, alpha: alpha)

            // The folded value should match the next layer
            if round + 1 < proof.commitment.layers.count {
                let nextLayer = proof.commitment.layers[round + 1]
                let positionInNextLayer = position >> (round + 1)
                if nextLayer[positionInNextLayer % nextLayer.count] != expected {
                    return false
                }
            }
        }

        return true
    }

    /// Validate basic proof structure.
    private func validateProofStructure(_ proof: BinaryFRIProof<B>) -> Bool {
        // Check number of layers matches numRounds
        guard proof.commitment.layers.count == proof.numRounds + 1 else {
            return false
        }

        // Check layer sizes decrease correctly
        var expectedSize = 1 << proof.logDomainSize
        for round in 0...proof.numRounds {
            guard proof.commitment.layers[round].count == expectedSize else {
                return false
            }

            if round < proof.numRounds {
                let arity = determineArityForRound(round, logDomainSize: proof.logDomainSize,
                                                  finalPolyMaxDegree: proof.config.finalPolyMaxDegree,
                                                  foldingFactor: proof.config.foldingFactor)
                expectedSize >>= arity
            }
        }

        // Check alphas count matches rounds
        guard proof.commitment.alphas.count == proof.numRounds else {
            return false
        }

        return true
    }

    /// Verify the final polynomial degree is within bounds.
    private func verifyDegreeBound(proof: BinaryFRIProof<B>) -> Bool {
        let finalLayer = proof.commitment.layers.last
        guard let final = finalLayer else { return false }

        // Final layer size should be <= 2 * finalPolyMaxDegree + 1
        // because a degree-d polynomial has d+1 coefficients
        let maxSize = (1 << proof.config.finalPolyMaxDegree) + 1
        return final.count <= maxSize
    }

    /// Verify co-curvilinearity constraints.
    private func verifyCoCurvilinearity(proof: BinaryFRIProof<B>,
                                        openings: [BinaryFRIOpeningProof<B>]) -> Bool {
        // For each query position, verify the co-curvilinearity of
        // the folded values at that position across rounds
        for opening in openings {
            // Collect values at this position across layers
            var values = [B]()
            for (round, layerEval) in opening.layerEvals.enumerated() {
                let layerSize = 1 << (proof.logDomainSize - round)
                let idx = opening.initialPosition % layerSize

                // For fold-by-2, we have two values
                values.append(layerEval.0)
                values.append(layerEval.1)
            }

            // Test co-curvilinearity
            // In binary fields, we test that the values lie on an affine line
            // using the trace-based quadratic form
            let numPoints = min(values.count, coCurvilinear.numPoints)
            let pointsToTest = Array(values.prefix(numPoints))

            if pointsToTest.count >= 2 {
                let p0 = pointsToTest[0]
                let p1 = pointsToTest[1]
                let direction = p0 + p1  // In char 2, subtraction = addition

                if !coCurvilinear.test(points: pointsToTest,
                                       linePoint: p0,
                                       lineDirection: direction) {
                    return false
                }
            }
        }

        return true
    }

    // MARK: - Query Position Generation

    /// Generate query positions using Fiat-Shamir.
    public func generateQueryPositions(proof: BinaryFRIProof<B>,
                                       initialRoot: Data) -> [Int] {
        var transcript = BinaryFRITranscript(seed: Array(initialRoot))
        transcript.update([0x03])  // Domain separator for queries

        var positions = [Int]()
        let domainSize = 1 << proof.logDomainSize

        for _ in 0..<numQueries {
            let squeezed = transcript.squeeze(numBytes: 4)
            let value = squeezed.withUnsafeBytes { $0.load(as: UInt32.self) }
            let pos = Int(value) % domainSize
            positions.append(pos)
        }

        return positions
    }

    // MARK: - Soundness Checking

    /// Check if the proof achieves the desired soundness.
    public func achievesSoundness(proof: BinaryFRIProof<B>,
                                  securityBits: Int) -> Bool {
        // For Johnson bound decoding:
        // Soundness error = L / 2^m where L is list size, m is extension degree
        // We need: L / 2^m <= 2^{-securityBits}
        // So: m >= securityBits + log2(L)

        let logDomainSize = proof.logDomainSize
        let requiredM = securityBits + Int(log2(Double(config.numQueries)))

        return logDomainSize >= requiredM
    }

    /// Estimate the soundness error for this proof.
    public func soundnessError(proof: BinaryFRIProof<B>) -> Double {
        // Soundness error = L / 2^m
        let m = Double(proof.logDomainSize)
        let L = Double(config.numQueries)

        return L / pow(2.0, m)
    }

    // MARK: - Helper Methods

    /// Determine arity for a given round.
    private func determineArityForRound(_ round: Int,
                                         logDomainSize: Int,
                                         finalPolyMaxDegree: Int,
                                         foldingFactor: Int) -> Int {
        let maxArity = foldingFactor.trailingZeroBitCount
        let remainingRounds = logDomainSize - finalPolyMaxDegree - round

        return min(maxArity, max(1, remainingRounds))
    }
}

// MARK: - Proximity Gap Verification

/// Verifier extension for proximity gap analysis.
public extension BinaryFRIVerifierEngine {

    /// Verify that the proof is within the proximity gap.
    ///
    /// Returns (isWithinGap, distanceEstimate)
    func verifyProximityGap(proof: BinaryFRIProof<B>,
                            openings: [BinaryFRIOpeningProof<B>],
                            queryPositions: [Int]) -> (isWithinGap: Bool, distanceEstimate: Int) {
        // Estimate the distance to the nearest codeword based on
        // how well the openings match the fold equations

        var maxDeviation = 0

        for opening in openings {
            for (round, (f0, f1)) in opening.layerEvals.enumerated() {
                guard round < proof.commitment.alphas.count else { continue }

                let alpha = proof.commitment.alphas[round]
                let expected = foldEngine.splitEvenOdd(fx: f0, fx1: f1, alpha: alpha)

                if round + 1 < proof.commitment.layers.count {
                    let nextLayer = proof.commitment.layers[round + 1]
                    let posInNext = opening.initialPosition >> (round + 1)
                    let actual = nextLayer[posInNext % nextLayer.count]

                    // Count differing bits
                    let diff = f0.toGF8 ^ actual.toGF8
                    let bitsDifferent = diff.nonzeroBitCount
                    maxDeviation = max(maxDeviation, bitsDifferent)
                }
            }
        }

        let isWithinGap = maxDeviation <= decoder.params.johnsonRadius

        return (isWithinGap, maxDeviation)
    }
}

// MARK: - Batch Verification

/// Batch verifier for multiple proofs.
public struct BinaryFRIBatchVerifier<B: BinaryTowerProtocol> {

    /// Individual verifier engine
    public let verifier: BinaryFRIVerifierEngine<B>

    public init(config: BinaryFRIConfig) {
        self.verifier = BinaryFRIVerifierEngine<B>(config: config)
    }

    /// Verify multiple proofs in batch.
    ///
    /// Batch verification is more efficient than individual verification
    /// when proofs share common structure.
    ///
    /// - Parameter proofs: Array of (proof, openings, positions) tuples
    /// - Returns: True if all proofs are valid
    public func verifyBatch(proofs: [(BinaryFRIProof<B>, [BinaryFRIOpeningProof<B>], [Int])]) -> Bool {
        // Simple batch verification: verify each proof
        // More advanced batch verification could use random linear combinations
        for (proof, openings, positions) in proofs {
            if !verifier.verify(proof: proof, openings: openings, queryPositions: positions) {
                return false
            }
        }
        return true
    }

    /// Estimate total verification cost.
    public func estimateVerificationCost(numProofs: Int, queriesPerProof: Int) -> Int {
        // Rough estimate: each query verification costs O(log domain size)
        // Total is proportional to numProofs * queriesPerProof * logDomainSize
        return numProofs * queriesPerProof * verifier.config.logDomainSize
    }
}
