// zkMetal Test Suite — run with: swift build && .build/debug/zkMetalTests
// Or: swift build -c release && .build/release/zkMetalTests

import Foundation

let t0 = CFAbsoluteTimeGetCurrent()

runFieldTests()
runNTTTests()
runHashTests()
runMSMTests()
runPolynomialTests()
runProofSystemTests()
runGKRTests()
runDataParallelTests()
runSerializationTests()
runPlonkTests()
runCircleSTARKTests()
runGroth16ProverTests()
runUnifiedLookupTests()
runMultiMSMTests()
runWitnessGenTests()
runProtogalaxyTests()
runIVCTests()
runCircomParserTests()
runPlonky2RecursiveTests()
runSpartanTests()
runConstraintOptimizerTests()
runCosetLDETests()
runAIRDSLTests()
runPlonkGateTests()
runTranscriptTests()
runGPUBufferPoolTests()
runPoseidon2SpongeTests()
runGroth16SolidityTests()
runPedersenEngineTests()
runTraceCompressionTests()
runDASTests()
runUniversalProofFormatTests()
runPlonkPermutationTests()
runRISCVDecoderTests()
runVerkleProofTests()
runMultilinearTests()
runBatchKZGTests()
runPrefixScanTests()
runMemoryCheckingTests()
runRISCVExecutorTests()
runBinaryTowerTests()

let elapsed = CFAbsoluteTimeGetCurrent() - t0
print(String(format: "\nCompleted in %.1fs", elapsed))
printSummary()
