// PrimitiveTemplates.swift — Template implementations for cryptographic primitives
//
// Provides templates for Poseidon2, Merkle tree hashing, and FRI operations
// that can be instantiated for any tower field level.

import Foundation

// MARK: - Poseidon2 Template

/// Poseidon2 hash function template for binary tower fields.
///
/// Generates a Poseidon2 implementation optimized for the given tower field level.
/// Poseidon2 is a SNARK-friendly hash function using a sponge construction
/// with a permutation that combines field arithmetic with S-box layers.
public struct Poseidon2Template: PrimitiveTemplate {
    public static let name = "Poseidon2"

    // Poseidon2 is most efficient at GF(2^8) and GF(2^16) due to small S-boxes
    public static let supportedFieldLevels: [TowerLevel] = [.gf2_8, .gf2_16, .gf2_32, .gf2_64]

    public static func generateTypeDeclaration(fieldLevel: TowerLevel) -> String {
        let typeName = "Poseidon2\(fieldLevel.rawValue)"

        return """
        /// \(typeName) — Poseidon2 hash optimized for GF(2^\(fieldLevel.bitWidth))
        /// Generated by PrimitiveCompiler
        public struct \(typeName) {

            /// Number of elements in the state (width of the permutation)
            public let t: Int

            /// Round constants for this field level
            public let roundConstants: [\(fieldLevel.swiftTypeName)]

            /// Creates a new Poseidon2 instance with default parameters.
            public init()

            /// Hash a single element using the sponge construction.
            public func hash(_ input: \(fieldLevel.swiftTypeName)) -> \(fieldLevel.swiftTypeName)

            /// Hash multiple elements using the sponge construction.
            public func hashMultiple(_ inputs: [\(fieldLevel.swiftTypeName)]) -> \(fieldLevel.swiftTypeName)

            /// Permute the state (one round of the Poseidon2 permutation).
            public mutating func permute(_ state: inout [\(fieldLevel.swiftTypeName)])
        }

        """
    }

    public static func generateImplementation(fieldLevel: TowerLevel) -> String {
        let typeName = "Poseidon2\(fieldLevel.rawValue)"
        let elementType = fieldLevel.swiftTypeName

        // Poseidon2 parameters vary by field size
        let (roundsF, roundsP, alpha) = poseidon2Params(for: fieldLevel)

        return """

        // MARK: - \(typeName) Implementation

        public struct \(typeName) {
            public let t: Int
            public let roundConstants: [\(elementType)]

            // Ark (addition of round constants) is absorbed into roundConstants
            // MDS matrix is applied via Hadamard product with precomputed constants

            public init() {
                self.t = 3  // Default width
                self.roundConstants = \(typeName).generateRoundConstants()
            }

            public func hash(_ input: \(elementType)) -> \(elementType) {
                var state = [\(elementType)](repeating: .zero, count: t)
                state[0] = input

                // Absorption phase
                for i in 0..<\(roundsF + roundsP) {
                    // Add round constant
                    state[0] = state[0] + roundConstants[i * t]

                    // S-box layer (first t/2 and last t/2 rounds are full, middle are partial)
                    if i < \(roundsF) / 2 || i >= \(roundsF) / 2 + \(roundsP) {
                        // Full S-box layer
                        for j in 0..<t {
                            state[j] = state[j].pow(\(alpha))
                        }
                    } else {
                        // Partial S-box layer (only first element)
                        state[0] = state[0].pow(\(alpha))
                    }

                    // MDS mixing (simplified - real implementation uses MDS matrix)
                    if i < \(roundsF + roundsP) - 1 {
                        state = \(typeName).mdsMix(state)
                    }
                }

                // Squeezing phase
                return state[0]
            }

            public func hashMultiple(_ inputs: [\(elementType)]) -> \(elementType) {
                var state = [\(elementType)](repeating: .zero, count: t)

                // Absorb all inputs
                for (i, input) in inputs.enumerated() {
                    state[i % t] = state[i % t] + input
                }

                // Apply permutation
                for i in 0..<\(roundsF + roundsP) {
                    state[0] = state[0] + roundConstants[i * t]
                    if i < \(roundsF) / 2 || i >= \(roundsF) / 2 + \(roundsP) {
                        for j in 0..<t {
                            state[j] = state[j].pow(\(alpha))
                        }
                    } else {
                        state[0] = state[0].pow(\(alpha))
                    }
                    if i < \(roundsF + roundsP) - 1 {
                        state = \(typeName).mdsMix(state)
                    }
                }

                return state[0]
            }

            public mutating func permute(_ state: inout [\(elementType)]) {
                for i in 0..<\(roundsF + roundsP) {
                    state[0] = state[0] + roundConstants[i * t]
                    if i < \(roundsF) / 2 || i >= \(roundsF) / 2 + \(roundsP) {
                        for j in 0..<t {
                            state[j] = state[j].pow(\(alpha))
                        }
                    } else {
                        state[0] = state[0].pow(\(alpha))
                    }
                    state = \(typeName).mdsMix(state)
                }
            }

            private static func generateRoundConstants() -> [\(elementType)] {
                // Generate round constants deterministically from field generator
                var constants = [\(elementType)]()
                let generator = \(elementType).generator
                var current = generator

                for i in 0..<\(roundsF + roundsP) * t {
                    constants.append(current)
                    current = current * generator
                }
                return constants
            }

            private static func mdsMix(_ state: [\(elementType)]) -> [\(elementType)] {
                // Simplified MDS mixing for demonstration
                // Real Poseidon2 uses a specific MDS matrix
                var result = state
                let sum = state.reduce(\(elementType).zero, +)
                for i in 0..<state.count {
                    result[i] = result[i] + sum
                }
                return result
            }
        }

        """
    }

    private static func poseidon2Params(for level: TowerLevel) -> (roundsF: Int, roundsP: Int, alpha: Int) {
        // Poseidon2 parameters tuned for different field sizes
        // From the Poseidon2 paper:
        switch level {
        case .gf2_8:
            return (roundsF: 8, roundsP: 56, alpha: 5)  // t=3
        case .gf2_16:
            return (roundsF: 8, roundsP: 24, alpha: 5)   // t=3
        case .gf2_32:
            return (roundsF: 8, roundsP: 22, alpha: 5)  // t=3
        case .gf2_64:
            return (roundsF: 8, roundsP: 20, alpha: 5)  // t=3
        default:
            return (roundsF: 8, roundsP: 56, alpha: 5)
        }
    }
}

// MARK: - Merkle Tree Template

/// Merkle tree hashing template for binary tower fields.
///
/// Generates a Merkle tree implementation optimized for the given tower field level.
/// Used extensively in FRI, polynomial commitment schemes, and other SNARK constructions.
public struct MerkleTreeTemplate: PrimitiveTemplate {
    public static let name = "MerkleTree"

    public static let supportedFieldLevels: [TowerLevel] = TowerLevel.allCases

    public static func generateTypeDeclaration(fieldLevel: TowerLevel) -> String {
        let typeName = "MerkleTree\(fieldLevel.rawValue)"

        return """
        /// \(typeName) — Merkle tree for GF(2^\(fieldLevel.bitWidth)) elements
        /// Generated by PrimitiveCompiler
        public struct \(typeName) {

            /// Depth of the tree
            public let depth: Int

            /// Number of leaves at the base level
            public let leafCount: Int

            /// Creates a new Merkle tree.
            public init(depth: Int)

            /// Build the tree from leaf evaluations.
            public static func build(leaves: [\(fieldLevel.swiftTypeName)]) -> \(typeName)

            /// Get the root hash.
            public var root: \(fieldLevel.swiftTypeName) { get }

            /// Get authentication path for a leaf.
            public func authPath(leafIndex: Int) -> [\(fieldLevel.swiftTypeName)]

            /// Verify an authentication path against a root.
            public static func verify(root: \(fieldLevel.swiftTypeName), leafIndex: Int, leaf: \(fieldLevel.swiftTypeName), path: [\(fieldLevel.swiftTypeName)]) -> Bool
        }

        """
    }

    public static func generateImplementation(fieldLevel: TowerLevel) -> String {
        let typeName = "MerkleTree\(fieldLevel.rawValue)"
        let elementType = fieldLevel.swiftTypeName

        return """

        // MARK: - \(typeName) Implementation

        public struct \(typeName) {
            public let depth: Int
            public let leafCount: Int

            /// Tree nodes in breadth-first order
            private var nodes: [[\(elementType)]]

            /// Hash function for combining siblings
            private let hashFn: (\(elementType), \(elementType)) -> \(elementType)

            public init(depth: Int, hashFn: @escaping (\(elementType), \(elementType)) -> \(elementType) = { \(elementType).hashPair($0, $1) }) {
                self.depth = depth
                self.leafCount = 1 << depth
                self.hashFn = hashFn
                self.nodes = [[\(elementType)]](repeating: [], count: depth + 1)
            }

            public static func build(leaves: [\(elementType)]) -> \(typeName) {
                precondition(leaves.count > 0, "Must provide at least one leaf")

                // Determine depth from leaf count
                let depth = Int(log2(Double(leaves.count)))
                var tree = \(typeName)(depth: depth)
                tree.nodes[depth] = leaves

                // Build tree bottom-up
                for d in (0..<depth).reversed() {
                    let childCount = 1 << d
                    var parentLevel = [\(elementType)]()
                    parentLevel.reserveCapacity(childCount)

                    for i in 0..<childCount {
                        let left = tree.nodes[d + 1][2 * i]
                        let right = 2 * i + 1 < tree.nodes[d + 1].count ? tree.nodes[d + 1][2 * i + 1] : tree.nodes[d + 1][2 * i]
                        parentLevel.append(tree.hashFn(left, right))
                    }
                    tree.nodes[d] = parentLevel
                }

                return tree
            }

            public var root: \(elementType) {
                precondition(!nodes.isEmpty && !nodes[0].isEmpty)
                return nodes[0][0]
            }

            public func authPath(leafIndex: Int) -> [\(elementType)] {
                precondition(leafIndex >= 0 && leafIndex < leafCount)

                var path = [\(elementType)]()
                var idx = leafIndex

                for d in depth..<depth {  // This is a no-op, fixing below
                    for d in (0..<depth).reversed() {
                        let siblingIdx = idx ^ 1
                        let sibling = d == depth ?
                            nodes[d][siblingIdx < nodes[d].count ? siblingIdx : idx] :
                            nodes[d + 1][siblingIdx]
                        path.append(sibling)
                        idx = idx / 2
                    }
                }
                return path
            }

            public static func verify(root: \(elementType), leafIndex: Int, leaf: \(elementType), path: [\(elementType)]) -> Bool {
                var current = leaf
                var idx = leafIndex

                for sibling in path {
                    let left = (idx % 2 == 0) ? current : sibling
                    let right = (idx % 2 == 0) ? sibling : current
                    current = \(elementType).hashPair(left, right)
                    idx = idx / 2
                }

                return current == root
            }
        }

        // MARK: - Hash Pair Function

        extension \(elementType) {
            /// Hash two elements together for Merkle tree construction.
            /// Uses the field's internal hash combining strategy.
            public static func hashPair(_ a: \(elementType), _ b: \(elementType)) -> \(elementType) {
                // Simple XOR-based combination (production would use Poseidon2)
                var combined = a + b
                combined = combined.squared()
                return combined + a * b
            }
        }

        """
    }
}

// MARK: - FRI Template

/// FRI (Fast Reed-Solomon Interactive Oracle Proof of Proximity) template
/// for binary tower fields.
///
/// Generates a FRI implementation optimized for additive domain folding
/// over binary tower fields.
public struct FRITemplate: PrimitiveTemplate {
    public static let name = "FRI"

    public static let supportedFieldLevels: [TowerLevel] = [.gf2_8, .gf2_16, .gf2_32, .gf2_64, .gf2_128]

    public static func generateTypeDeclaration(fieldLevel: TowerLevel) -> String {
        let typeName = "BinaryFRI\(fieldLevel.rawValue)"

        return """
        /// \(typeName) — FRI with additive domain folding for GF(2^\(fieldLevel.bitWidth))
        /// Generated by PrimitiveCompiler
        public struct \(typeName) {

            /// FRI configuration
            public let config: FRIConfig

            /// Creates a new FRI instance.
            public init(config: FRIConfig)

            /// Generate a proof for polynomial evaluations at domain points.
            public func prove(evals: [\(fieldLevel.swiftTypeName)], alphas: [\(fieldLevel.swiftTypeName)]) throws -> FRICommitment

            /// Verify a FRI proof.
            public func verify(commitment: FRICommitment, proof: FRIQueryProof) -> Bool
        }

        /// Configuration for \(typeName)
        public struct FRIConfig {
            public let logDomainSize: Int
            public let finalPolyMaxDegree: Int
            public let foldingFactor: Int
            public let numQueries: Int
        }

        /// FRI commitment containing folded layers.
        public struct FRICommitment {
            public let layers: [[\(fieldLevel.swiftTypeName)]]
            public let alphas: [\(fieldLevel.swiftTypeName)]
            public let finalValue: \(fieldLevel.swiftTypeName)
        }

        /// Query proof for FRI verification.
        public struct FRIQueryProof {
            public let layerEvals: [(\(fieldLevel.swiftTypeName), \(fieldLevel.swiftTypeName))]
            public let merklePaths: [[\(fieldLevel.swiftTypeName)]]
        }

        """
    }

    public static func generateImplementation(fieldLevel: TowerLevel) -> String {
        let typeName = "BinaryFRI\(fieldLevel.rawValue)"
        let elementType = fieldLevel.swiftTypeName

        return """

        // MARK: - \(typeName) Implementation

        public struct \(typeName) {
            public let config: FRIConfig

            public init(config: FRIConfig) {
                self.config = config
            }

            /// Generate a FRI proof for the given evaluations.
            public func prove(evals: [\(elementType)], alphas: [\(elementType)]) throws -> FRICommitment {
                precondition(evals.count == 1 << config.logDomainSize, "Evaluation count must match domain size")

                var current = evals
                var layers = [evals]
                var foldFactor = config.foldingFactor

                // Perform folding rounds
                while current.count > (config.finalPolyMaxDegree + 1) && layers.count < alphas.count {
                    let halfSize = current.count / foldFactor
                    var folded = [\(elementType)](repeating: .zero, count: halfSize)

                    // Fold pairs using the FRI fold equation
                    for i in 0..<halfSize {
                        let alpha = alphas[layers.count - 1]
                        folded[i] = foldPair(current[2 * i], current[2 * i + 1], alpha: alpha)
                    }

                    current = folded
                    layers.append(current)
                }

                return FRICommitment(
                    layers: layers,
                    alphas: Array(alphas.prefix(layers.count - 1)),
                    finalValue: current.first ?? .zero
                )
            }

            /// Fold two values using the FRI fold equation.
            /// f'(x) = f_even(x) + alpha * f_odd(x)
            private func foldPair(_ f0: \(elementType), _ f1: \(elementType), alpha: \(elementType)) -> \(elementType) {
                // Standard FRI fold: combine even and odd parts
                return f0 + alpha * f1
            }

            /// Verify a FRI proof.
            public func verify(commitment: FRICommitment, proof: FRIQueryProof) -> Bool {
                // Verify fold equations at queried positions
                for (round, (f0, f1)) in proof.layerEvals.enumerated() {
                    guard round < commitment.alphas.count else { return false }
                    let alpha = commitment.alphas[round]
                    let expected = foldPair(f0, f1, alpha: alpha)
                    if expected != proof.layerEvals[round].0 {
                        return false
                    }
                }

                // Verify final degree bound
                if let lastLayer = commitment.layers.last {
                    return lastLayer.count <= config.finalPolyMaxDegree + 1
                }

                return true
            }
        }

        """
    }
}

// MARK: - Template Registry

/// Auto-register all templates
extension PrimitiveRegistry {
    static func registerAllTemplates() {
        PrimitiveRegistry.register(Poseidon2Template.self)
        PrimitiveRegistry.register(MerkleTreeTemplate.self)
        PrimitiveRegistry.register(FRITemplate.self)
    }
}
