// TowerFieldCodeGenerator.swift — Code generation for tower field implementations
//
// Generates optimized Swift implementations for binary tower fields.
// Exploits the tower structure for efficient arithmetic and can generate
// both CPU and GPU implementations with SIMD vectorization.

import Foundation

// MARK: - Tower Field Code Generator

/// Generates Swift code for binary tower field implementations.
///
/// The generator creates field types that exploit the tower structure
/// for efficient arithmetic. Each level doubles the extension degree
/// using the construction: GF(2^{2k}) = GF(2^k)[X] / (X^2 + X + alpha)
public final class TowerFieldCodeGenerator {

    /// Generated code output
    public private(set) var output: String = ""

    /// Current indentation level
    private var indentLevel: Int = 0

    /// Line terminator
    private let newline = "\n"

    public init() {}

    // MARK: - Code Generation Entry Points

    /// Generate a complete tower field implementation for a given level.
    /// - Parameter level: The tower level to generate
    /// - Returns: Swift source code for the field implementation
    public func generateField(level: TowerLevel) -> String {
        reset()

        switch level {
        case .gf2_1, .gf2_2, .gf2_4:
            // These use lookup-table based multiplication
            return generateSmallField(level: level)
        case .gf2_8:
            return generateGF8Implementation()
        case .gf2_16, .gf2_32, .gf2_64, .gf2_128:
            // These use Karatsuba multiplication with tower structure
            return generateTowerField(level: level)
        }
    }

    /// Generate field implementation for small fields (GF(2^1), GF(2^2), GF(2^4))
    /// that use lookup table multiplication.
    private func generateSmallField(level: TowerLevel) -> String {
        appendLine("/// \(level.swiftTypeName) — GF(2^\(level.bitWidth)) with lookup-table multiplication")
        appendLine("/// Generated by TowerFieldCodeGenerator")
        appendLine("")
        appendLine("import Foundation")
        appendLine("")

        appendLine("public struct \(level.swiftTypeName): BinaryTowerProtocol {")
        indent()

        // Property declarations
        appendLine("public var value: \(level.nativeIntegerType)")
        appendLine("")
        appendLine("public static let zero = \(level.swiftTypeName)(value: 0)")
        appendLine("public static let one = \(level.swiftTypeName)(value: 1)")
        appendLine("public static let extensionDegree = \(level.bitWidth)")
        appendLine("")

        // Init
        appendLine("public init(value: \(level.nativeIntegerType)) {")
        indent(); appendLine("self.value = value"); dedent()
        appendLine("}")
        appendLine("")

        // isZero
        appendLine("public var isZero: Bool { value == 0 }")
        appendLine("")

        // Addition (XOR)
        appendLine("@inline(__always)")
        appendLine("public static func + (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent(); appendLine("\(level.swiftTypeName)(value: a.value ^ b.value)"); dedent()
        appendLine("}")
        appendLine("")

        // Subtraction (same as addition in char 2)
        appendLine("@inline(__always)")
        appendLine("public static func - (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent(); appendLine("a + b"); dedent()
        appendLine("}")
        appendLine("")

        // Multiplication via lookup table
        let tableName = "GF\(level.bitWidth)Tables"
        appendLine("@inline(__always)")
        appendLine("public static func * (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent(); appendLine("\(level.swiftTypeName)(value: \(tableName).mul(a.value, b.value))"); dedent()
        appendLine("}")
        appendLine("")

        // Inverse
        appendLine("public func inverse() -> \(level.swiftTypeName) {")
        indent()
        appendLine("precondition(!isZero, \"Cannot invert zero\")")
        appendLine("return \(level.swiftTypeName)(value: \(tableName).inv(Int(value)))")
        dedent()
        appendLine("}")
        appendLine("")

        // Squared
        appendLine("@inline(__always)")
        appendLine("public func squared() -> \(level.swiftTypeName) {")
        indent(); appendLine("self * self"); dedent()
        appendLine("}")

        dedent()
        appendLine("}")

        return output
    }

    /// Generate GF(2^8) implementation with AES polynomial optimization.
    private func generateGF8Implementation() -> String {
        appendLine("/// BinaryTower8 — GF(2^8) with AES polynomial (x^8 + x^4 + x^3 + x + 1)")
        appendLine("/// Generated by TowerFieldCodeGenerator")
        appendLine("")
        appendLine("import Foundation")
        appendLine("import NeonFieldOps")
        appendLine("")

        appendLine("public struct BinaryTower8: BinaryTowerProtocol {")
        indent()

        appendLine("public var value: UInt8")
        appendLine("")
        appendLine("public static let zero = BinaryTower8(value: 0)")
        appendLine("public static let one = BinaryTower8(value: 1)")
        appendLine("public static let extensionDegree = 8")
        appendLine("public static let generator = BinaryTower8(value: 3)")
        appendLine("")

        // Init from GF8
        appendLine("public init(value: UInt8) {")
        indent(); appendLine("self.value = value"); dedent()
        appendLine("}")
        appendLine("")
        appendLine("public init(fromGF8 value: UInt8) {")
        indent(); appendLine("self.value = value"); dedent()
        appendLine("}")
        appendLine("")
        appendLine("public var toGF8: UInt8 { value }")
        appendLine("public var isZero: Bool { value == 0 }")
        appendLine("public var description: String { \"BT8(0x\\(String(value, radix: 16, uppercase: true)))\" }")
        appendLine("")

        // Addition
        appendLine("@inline(__always)")
        appendLine("public static func + (a: BinaryTower8, b: BinaryTower8) -> BinaryTower8 {")
        indent(); appendLine("BinaryTower8(value: a.value ^ b.value)"); dedent()
        appendLine("}")
        appendLine("")

        // Subtraction
        appendLine("@inline(__always)")
        appendLine("public static func - (a: BinaryTower8, b: BinaryTower8) -> BinaryTower8 {")
        indent(); appendLine("a + b"); dedent()
        appendLine("}")
        appendLine("")

        // Multiplication
        appendLine("@inline(__always)")
        appendLine("public static func * (a: BinaryTower8, b: BinaryTower8) -> BinaryTower8 {")
        indent(); appendLine("BinaryTower8(value: bt_gf8_mul(a.value, b.value))"); dedent()
        appendLine("}")
        appendLine("")

        // Inverse
        appendLine("public func inverse() -> BinaryTower8 {")
        indent()
        appendLine("precondition(!isZero, \"Cannot invert zero in GF(2^8)\")")
        appendLine("BinaryTower8(value: bt_gf8_inv(value))")
        dedent()
        appendLine("}")
        appendLine("")

        // Squared
        appendLine("@inline(__always)")
        appendLine("public func squared() -> BinaryTower8 {")
        indent(); appendLine("BinaryTower8(value: bt_gf8_sqr(value))"); dedent()
        appendLine("}")

        dedent()
        appendLine("}")

        return output
    }

    /// Generate tower field implementation for GF(2^16) and above.
    /// Uses Karatsuba multiplication to exploit the tower structure.
    private func generateTowerField(level: TowerLevel) -> String {
        let lowerLevel = TowerLevel(rawValue: level.rawValue / 2)!

        appendLine("/// \(level.swiftTypeName) — GF(2^\(level.bitWidth)) via Karatsuba over GF(2^\(lowerLevel.bitWidth))")
        appendLine("/// Generated by TowerFieldCodeGenerator")
        appendLine("/// Tower extension: X^2 + X + ALPHA where ALPHA is the irreducible polynomial constant")
        appendLine("")
        appendLine("import Foundation")
        appendLine("import NeonFieldOps")
        appendLine("")

        appendLine("public struct \(level.swiftTypeName): BinaryTowerProtocol {")
        indent()

        // Properties for tower representation (lo + hi * X)
        appendLine("public var lo: \(lowerLevel.swiftTypeName)  // coefficient of 1")
        appendLine("public var hi: \(lowerLevel.swiftTypeName)  // coefficient of X")
        appendLine("")

        // Extension parameter
        let alphaName: String
        switch level {
        case .gf2_16: alphaName = "ALPHA"
        case .gf2_32: alphaName = "BETA"
        case .gf2_64: alphaName = "GAMMA"
        case .gf2_128: alphaName = "DELTA"
        default: alphaName = "ALPHA"
        }

        appendLine("/// Tower extension parameter: X^2 + X + \(alphaName) = 0")
        if level == .gf2_16 {
            appendLine("public static let \(alphaName) = \(lowerLevel.swiftTypeName)(value: 0x2B)")
        } else if level == .gf2_32 {
            appendLine("public static let \(alphaName) = \(lowerLevel.swiftTypeName)(lo: \(lowerLevel.swiftTypeName)(value: 0x02), hi: \(lowerLevel.swiftTypeName)(value: 0x01))")
        } else {
            appendLine("public static let \(alphaName) = \(lowerLevel.swiftTypeName)(value: 0x0000000000000002)")
        }
        appendLine("")
        appendLine("public static let zero = \(level.swiftTypeName)(lo: .zero, hi: .zero)")
        appendLine("public static let one = \(level.swiftTypeName)(lo: .one, hi: .zero)")
        appendLine("public static let extensionDegree = \(level.bitWidth)")
        appendLine("")

        // Init methods
        appendLine("public init(lo: \(lowerLevel.swiftTypeName), hi: \(lowerLevel.swiftTypeName)) {")
        indent(); appendLine("self.lo = lo"); appendLine("self.hi = hi"); dedent()
        appendLine("}")
        appendLine("")

        appendLine("public init(value: \(level.nativeIntegerType)) {")
        indent()
        if level == .gf2_128 {
            appendLine("self.lo = \(lowerLevel.swiftTypeName)(value: value.0)")
            appendLine("self.hi = \(lowerLevel.swiftTypeName)(value: value.1)")
        } else {
            appendLine("self.lo = \(lowerLevel.swiftTypeName)(value: \(level.nativeIntegerType)(value & 0x\(String(repeating: "F", count: lowerLevel.bitWidth / 4))))")
            appendLine("self.hi = \(lowerLevel.swiftTypeName)(value: \(level.nativeIntegerType)(value >> \(lowerLevel.bitWidth)))")
        }
        dedent()
        appendLine("}")
        appendLine("")

        // isZero
        appendLine("public var isZero: Bool { lo.isZero && hi.isZero }")
        appendLine("")

        // Addition
        appendLine("@inline(__always)")
        appendLine("public static func + (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent(); appendLine("\(level.swiftTypeName)(lo: a.lo + b.lo, hi: a.hi + b.hi)"); dedent()
        appendLine("}")
        appendLine("")

        // Subtraction
        appendLine("@inline(__always)")
        appendLine("public static func - (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent(); appendLine("a + b  // char 2: subtraction = addition"); dedent()
        appendLine("}")
        appendLine("")

        // Karatsuba multiplication
        appendLine("// Karatsuba multiplication: (a + bX)(c + dX) = ac + bd·α + ((a+b)(c+d) + ac)·X")
        appendLine("@inline(__always)")
        appendLine("public static func * (a: \(level.swiftTypeName), b: \(level.swiftTypeName)) -> \(level.swiftTypeName) {")
        indent()
        appendLine("let ac = a.lo * b.lo")
        appendLine("let bd = a.hi * b.hi")
        appendLine("let e = (a.lo + a.hi) * (b.lo + b.hi)")
        appendLine("let bdAlpha = bd * \(level.swiftTypeName).\(alphaName)")
        appendLine("return \(level.swiftTypeName)(lo: ac + bdAlpha, hi: e + ac)")
        dedent()
        appendLine("}")
        appendLine("")

        // Inverse
        appendLine("public func inverse() -> \(level.swiftTypeName) {")
        indent()
        appendLine("precondition(!isZero, \"Cannot invert zero in GF(2^\(level.bitWidth))\")")
        appendLine("// For (a + bX), inverse uses norm: N = a² + a·b + b²·α")
        appendLine("let a2 = lo * lo")
        appendLine("let ab = lo * hi")
        appendLine("let b2Alpha = hi * hi * \(level.swiftTypeName).\(alphaName)")
        appendLine("let norm = a2 + ab + b2Alpha")
        appendLine("let normInv = norm.inverse()")
        appendLine("return \(level.swiftTypeName)(lo: (lo + hi) * normInv, hi: hi * normInv)")
        dedent()
        appendLine("}")
        appendLine("")

        // Squared
        appendLine("@inline(__always)")
        appendLine("public func squared() -> \(level.swiftTypeName) { self * self }")

        dedent()
        appendLine("}")

        return output
    }

    // MARK: - Helper Methods

    private func reset() {
        output = ""
        indentLevel = 0
    }

    private func appendLine(_ line: String) {
        let indent = String(repeating: "    ", count: indentLevel)
        output += indent + line + newline
    }

    private func indent() {
        indentLevel += 1
    }

    private func dedent() {
        indentLevel = max(0, indentLevel - 1)
    }
}

// MARK: - Batch Operations Generator

/// Generates batch operation implementations for improved throughput.
public final class BatchOperationsGenerator {

    /// Generate batch multiply implementation for a field level.
    public func generateBatchMultiply(level: TowerLevel) -> String {
        let elementType = level.swiftTypeName

        var output = ""

        output += "    // MARK: - Batch Operations\n\n"

        switch level {
        case .gf2_64:
            output += """
                /// Batch GF(2^64) multiply: out[i] = a[i] * b[i]
                public static func batchMultiply(_ a: [UInt64], _ b: [UInt64]) -> [UInt64] {
                    precondition(a.count == b.count)
                    var out = [UInt64](repeating: 0, count: a.count)
                    bt_gf64_batch_mul(a, b, &out, Int32(a.count))
                    return out
                }

                /// Batch GF(2^64) add (XOR): out[i] = a[i] ^ b[i]
                public static func batchAdd(_ a: [UInt64], _ b: [UInt64]) -> [UInt64] {
                    precondition(a.count == b.count)
                    var out = [UInt64](repeating: 0, count: a.count)
                    bt_gf64_batch_add(a, b, &out, Int32(a.count))
                    return out
                }

            """

        case .gf2_128:
            output += """
                /// Batch GF(2^128) multiply: out[i] = a[i] * b[i]
                /// Input/output arrays interleave lo/hi: [a0_lo, a0_hi, a1_lo, a1_hi, ...]
                public static func batchMultiply(_ a: [UInt64], _ b: [UInt64]) -> [UInt64] {
                    precondition(a.count == b.count)
                    precondition(a.count % 2 == 0)
                    var out = [UInt64](repeating: 0, count: a.count)
                    bt_gf128_batch_mul(a, b, &out, Int32(a.count / 2))
                    return out
                }

                /// Batch GF(2^128) add (XOR)
                public static func batchAdd(_ a: [UInt64], _ b: [UInt64]) -> [UInt64] {
                    precondition(a.count == b.count)
                    precondition(a.count % 2 == 0)
                    var out = [UInt64](repeating: 0, count: a.count)
                    bt_gf128_batch_add(a, b, &out, Int32(a.count / 2))
                    return out
                }

            """

        default:
            // Generic Swift implementation for smaller fields
            output += """
                /// Batch multiply for GF(2^\(level.bitWidth))
                public static func batchMultiply(_ a: [\(elementType)], _ b: [\(elementType)]) -> [\(elementType)] {
                    precondition(a.count == b.count)
                    return zip(a, b).map { $0 * $1 }
                }

                /// Batch add for GF(2^\(level.bitWidth))
                public static func batchAdd(_ a: [\(elementType)], _ b: [\(elementType)]) -> [\(elementType)] {
                    precondition(a.count == b.count)
                    return zip(a, b).map { $0 + $1 }
                }

            """
        }

        return output
    }
}
