// Groth16 Solidity verifier generation and Ethereum-compatible serialization.
// Generates complete Solidity contracts using EVM bn256 precompiles (ecAdd 0x06,
// ecMul 0x07, ecPairing 0x08) for on-chain verification of zkMetal Groth16 proofs.
// Supports snarkjs-compatible JSON export/import and binary serialization.

import Foundation

// MARK: - Export Formats

/// Serialization format for Groth16 verification keys and proofs.
public enum Groth16ExportFormat {
    case json       // snarkjs-compatible JSON
    case solidity   // Solidity verifier contract source
    case binary     // Compact binary (32-byte BE words)
}

// MARK: - Solidity Verifier Generation

/// Generate a complete Solidity verifier contract for a specific Groth16 verification key.
/// Uses EVM precompiled contracts: ecAdd (0x06), ecMul (0x07), ecPairing (0x08).
public func generateSolidityVerifier(vk: Groth16VerificationKey) -> String {
    // Convert VK points to affine decimal strings for embedding
    guard let alphaAff = pointToAffine(vk.alpha_g1) else { return "// Error: alpha_g1 is identity" }
    guard let betaAff = g2ToAffine(vk.beta_g2) else { return "// Error: beta_g2 is identity" }
    guard let gammaAff = g2ToAffine(vk.gamma_g2) else { return "// Error: gamma_g2 is identity" }
    guard let deltaAff = g2ToAffine(vk.delta_g2) else { return "// Error: delta_g2 is identity" }

    let nPublic = vk.ic.count - 1

    // Collect IC points as affine
    var icAffines = [(String, String)]()
    for i in 0..<vk.ic.count {
        if let aff = pointToAffine(vk.ic[i]) {
            icAffines.append((fpToDecimal(aff.x), fpToDecimal(aff.y)))
        } else {
            icAffines.append(("0", "0"))
        }
    }

    // Build Solidity source
    var s = ""
    s += "// SPDX-License-Identifier: MIT\n"
    s += "pragma solidity ^0.8.0;\n\n"
    s += "/// @title Groth16 Verifier (generated by zkMetal)\n"
    s += "/// @notice Verifies Groth16 proofs on BN254 using EVM precompiles\n"
    s += "contract Groth16Verifier {\n"
    s += "    uint256 constant PRIME_Q = 21888242871839275222246405745257275088696311157297823662689037894645226208583;\n\n"

    // Verification key constants
    s += "    // Verification Key\n"
    s += "    uint256 constant ALPHA_X = \(fpToDecimal(alphaAff.x));\n"
    s += "    uint256 constant ALPHA_Y = \(fpToDecimal(alphaAff.y));\n\n"

    s += "    uint256 constant BETA_X1 = \(fpToDecimal(betaAff.x.c0));\n"
    s += "    uint256 constant BETA_X2 = \(fpToDecimal(betaAff.x.c1));\n"
    s += "    uint256 constant BETA_Y1 = \(fpToDecimal(betaAff.y.c0));\n"
    s += "    uint256 constant BETA_Y2 = \(fpToDecimal(betaAff.y.c1));\n\n"

    s += "    uint256 constant GAMMA_X1 = \(fpToDecimal(gammaAff.x.c0));\n"
    s += "    uint256 constant GAMMA_X2 = \(fpToDecimal(gammaAff.x.c1));\n"
    s += "    uint256 constant GAMMA_Y1 = \(fpToDecimal(gammaAff.y.c0));\n"
    s += "    uint256 constant GAMMA_Y2 = \(fpToDecimal(gammaAff.y.c1));\n\n"

    s += "    uint256 constant DELTA_X1 = \(fpToDecimal(deltaAff.x.c0));\n"
    s += "    uint256 constant DELTA_X2 = \(fpToDecimal(deltaAff.x.c1));\n"
    s += "    uint256 constant DELTA_Y1 = \(fpToDecimal(deltaAff.y.c0));\n"
    s += "    uint256 constant DELTA_Y2 = \(fpToDecimal(deltaAff.y.c1));\n\n"

    // IC points
    for (i, (x, y)) in icAffines.enumerated() {
        s += "    uint256 constant IC\(i)_X = \(x);\n"
        s += "    uint256 constant IC\(i)_Y = \(y);\n"
    }
    s += "\n"

    // Negate function for G1 (BN254: -P.y = PRIME_Q - P.y)
    s += "    function negate(uint256 y) internal pure returns (uint256) {\n"
    s += "        if (y == 0) return 0;\n"
    s += "        return PRIME_Q - y;\n"
    s += "    }\n\n"

    // verifyProof function
    s += "    /// @notice Verify a Groth16 proof\n"
    s += "    /// @param a G1 point [a.x, a.y]\n"
    s += "    /// @param b G2 point [[b.x.c1, b.x.c0], [b.y.c1, b.y.c0]]\n"
    s += "    /// @param c G1 point [c.x, c.y]\n"
    s += "    /// @param input Public inputs array\n"
    s += "    function verifyProof(\n"
    s += "        uint256[2] memory a,\n"
    s += "        uint256[2][2] memory b,\n"
    s += "        uint256[2] memory c,\n"
    s += "        uint256[\(nPublic)] memory input\n"
    s += "    ) public view returns (bool) {\n"

    // Compute vk_x = IC[0] + sum(input[i] * IC[i+1])
    s += "        // Compute linear combination of public inputs with IC\n"
    s += "        uint256[2] memory vk_x = [IC0_X, IC0_Y];\n\n"

    for i in 0..<nPublic {
        s += "        // input[\(i)] * IC[\(i+1)]\n"
        s += "        {\n"
        s += "            uint256[3] memory mul_input;\n"
        s += "            mul_input[0] = IC\(i+1)_X;\n"
        s += "            mul_input[1] = IC\(i+1)_Y;\n"
        s += "            mul_input[2] = input[\(i)];\n"
        s += "            uint256[2] memory mul_result;\n"
        s += "            assembly {\n"
        s += "                // ecMul precompile at 0x07\n"
        s += "                let success := staticcall(gas(), 0x07, mul_input, 0x60, mul_result, 0x40)\n"
        s += "                if iszero(success) { revert(0, 0) }\n"
        s += "            }\n"
        s += "            // ecAdd: vk_x = vk_x + mul_result\n"
        s += "            uint256[4] memory add_input;\n"
        s += "            add_input[0] = vk_x[0];\n"
        s += "            add_input[1] = vk_x[1];\n"
        s += "            add_input[2] = mul_result[0];\n"
        s += "            add_input[3] = mul_result[1];\n"
        s += "            assembly {\n"
        s += "                // ecAdd precompile at 0x06\n"
        s += "                let success := staticcall(gas(), 0x06, add_input, 0x80, vk_x, 0x40)\n"
        s += "                if iszero(success) { revert(0, 0) }\n"
        s += "            }\n"
        s += "        }\n\n"
    }

    // Pairing check: e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1
    s += "        // Pairing check\n"
    s += "        uint256[24] memory pairing_input;\n"
    s += "        // e(-A, B)\n"
    s += "        pairing_input[0] = a[0];\n"
    s += "        pairing_input[1] = negate(a[1]);\n"
    s += "        pairing_input[2] = b[0][0];\n"
    s += "        pairing_input[3] = b[0][1];\n"
    s += "        pairing_input[4] = b[1][0];\n"
    s += "        pairing_input[5] = b[1][1];\n"
    s += "        // e(alpha, beta)\n"
    s += "        pairing_input[6] = ALPHA_X;\n"
    s += "        pairing_input[7] = ALPHA_Y;\n"
    s += "        pairing_input[8] = BETA_X2;\n"
    s += "        pairing_input[9] = BETA_X1;\n"
    s += "        pairing_input[10] = BETA_Y2;\n"
    s += "        pairing_input[11] = BETA_Y1;\n"
    s += "        // e(vk_x, gamma)\n"
    s += "        pairing_input[12] = vk_x[0];\n"
    s += "        pairing_input[13] = vk_x[1];\n"
    s += "        pairing_input[14] = GAMMA_X2;\n"
    s += "        pairing_input[15] = GAMMA_X1;\n"
    s += "        pairing_input[16] = GAMMA_Y2;\n"
    s += "        pairing_input[17] = GAMMA_Y1;\n"
    s += "        // e(C, delta)\n"
    s += "        pairing_input[18] = c[0];\n"
    s += "        pairing_input[19] = c[1];\n"
    s += "        pairing_input[20] = DELTA_X2;\n"
    s += "        pairing_input[21] = DELTA_X1;\n"
    s += "        pairing_input[22] = DELTA_Y2;\n"
    s += "        pairing_input[23] = DELTA_Y1;\n\n"

    s += "        uint256[1] memory pairing_result;\n"
    s += "        assembly {\n"
    s += "            // ecPairing precompile at 0x08\n"
    s += "            let success := staticcall(gas(), 0x08, pairing_input, 0x300, pairing_result, 0x20)\n"
    s += "            if iszero(success) { revert(0, 0) }\n"
    s += "        }\n"
    s += "        return pairing_result[0] == 1;\n"
    s += "    }\n"
    s += "}\n"

    return s
}

// MARK: - Verification Key Export/Import

/// Export a Groth16 verification key in the specified format.
public func exportVerificationKey(vk: Groth16VerificationKey, format: Groth16ExportFormat) -> Data? {
    switch format {
    case .json:
        return vk.toSnarkjsJSON()
    case .solidity:
        let source = generateSolidityVerifier(vk: vk)
        return source.data(using: .utf8)
    case .binary:
        return exportVKBinary(vk: vk)
    }
}

/// Import a Groth16 verification key from the specified format.
public func importVerificationKey(data: Data, format: Groth16ExportFormat) -> Groth16VerificationKey? {
    switch format {
    case .json:
        return Groth16VerificationKey.fromSnarkjsJSON(data)
    case .solidity:
        return nil  // Cannot parse Solidity back to VK
    case .binary:
        return importVKBinary(data: data)
    }
}

// MARK: - Proof Export

/// Export a Groth16 proof with public inputs in the specified format.
public func exportProof(proof: Groth16Proof, publicInputs: [Fr], format: Groth16ExportFormat) -> Data? {
    switch format {
    case .json:
        return exportProofJSON(proof: proof, publicInputs: publicInputs)
    case .solidity:
        // For .solidity, return the calldata hex string as UTF-8 data
        let calldata = generateCalldata(proof: proof, publicInputs: publicInputs)
        return calldata.data(using: .utf8)
    case .binary:
        return exportProofBinary(proof: proof, publicInputs: publicInputs)
    }
}

/// Generate hex-encoded calldata for the Solidity verifyProof function.
/// Includes the function selector and ABI-encoded proof + public inputs.
public func generateCalldata(proof: Groth16Proof, publicInputs: [Fr]) -> String {
    guard let aAff = pointToAffine(proof.a),
          let bAff = g2ToAffine(proof.b),
          let cAff = pointToAffine(proof.c) else { return "" }

    // ABI-encode: uint256[2] a, uint256[2][2] b, uint256[2] c, uint256[N] input
    var words = [String]()

    // a: [x, y]
    words.append(fpToHex32(aAff.x))
    words.append(fpToHex32(aAff.y))

    // b: [[x.c1, x.c0], [y.c1, y.c0]] -- imaginary part first per Ethereum convention
    words.append(fpToHex32(bAff.x.c1))
    words.append(fpToHex32(bAff.x.c0))
    words.append(fpToHex32(bAff.y.c1))
    words.append(fpToHex32(bAff.y.c0))

    // c: [x, y]
    words.append(fpToHex32(cAff.x))
    words.append(fpToHex32(cAff.y))

    // public inputs
    for input in publicInputs {
        words.append(frToHex32(input))
    }

    // Function selector for verifyProof(uint256[2],uint256[2][2],uint256[2],uint256[N])
    // Using standard selector 0x43753b4d
    let selector = "43753b4d"
    return "0x" + selector + words.joined()
}

// MARK: - JSON Export (snarkjs-compatible)

private func exportProofJSON(proof: Groth16Proof, publicInputs: [Fr]) -> Data? {
    // Build combined JSON with proof and public signals
    guard let aAff = pointToAffine(proof.a),
          let bAff = g2ToAffine(proof.b),
          let cAff = pointToAffine(proof.c) else { return nil }

    // snarkjs calldata format: proof + publicSignals in one JSON object
    let proofDict: [String: Any] = [
        "pi_a": [fpToDecimal(aAff.x), fpToDecimal(aAff.y), "1"],
        "pi_b": [
            [fpToDecimal(bAff.x.c0), fpToDecimal(bAff.x.c1)],
            [fpToDecimal(bAff.y.c0), fpToDecimal(bAff.y.c1)],
            ["1", "0"]
        ],
        "pi_c": [fpToDecimal(cAff.x), fpToDecimal(cAff.y), "1"],
        "protocol": "groth16"
    ]

    let publicSignals = publicInputs.map { frToDecimal($0) }

    let combined: [String: Any] = [
        "proof": proofDict,
        "publicSignals": publicSignals
    ]

    return try? JSONSerialization.data(withJSONObject: combined,
                                       options: [.prettyPrinted, .sortedKeys])
}

// MARK: - Binary Serialization

// Binary VK format:
//   4 bytes: nPublic (LE uint32)
//   64 bytes: alpha_g1 (x, y as 32-byte BE words)
//   128 bytes: beta_g2 (x.c0, x.c1, y.c0, y.c1)
//   128 bytes: gamma_g2
//   128 bytes: delta_g2
//   (nPublic+1) * 64 bytes: IC points

private func exportVKBinary(vk: Groth16VerificationKey) -> Data? {
    guard let alphaAff = pointToAffine(vk.alpha_g1),
          let betaAff = g2ToAffine(vk.beta_g2),
          let gammaAff = g2ToAffine(vk.gamma_g2),
          let deltaAff = g2ToAffine(vk.delta_g2) else { return nil }

    let nPublic = UInt32(vk.ic.count - 1)
    var data = [UInt8]()
    let totalSize = 4 + 64 + 128 * 3 + Int(vk.ic.count) * 64
    data.reserveCapacity(totalSize)

    // nPublic (LE)
    data.append(UInt8(nPublic & 0xFF))
    data.append(UInt8((nPublic >> 8) & 0xFF))
    data.append(UInt8((nPublic >> 16) & 0xFF))
    data.append(UInt8((nPublic >> 24) & 0xFF))

    // alpha_g1
    data.append(contentsOf: fpToBE32(alphaAff.x))
    data.append(contentsOf: fpToBE32(alphaAff.y))

    // beta_g2, gamma_g2, delta_g2
    for g2Aff in [betaAff, gammaAff, deltaAff] {
        data.append(contentsOf: fpToBE32(g2Aff.x.c0))
        data.append(contentsOf: fpToBE32(g2Aff.x.c1))
        data.append(contentsOf: fpToBE32(g2Aff.y.c0))
        data.append(contentsOf: fpToBE32(g2Aff.y.c1))
    }

    // IC points
    for ic in vk.ic {
        if let aff = pointToAffine(ic) {
            data.append(contentsOf: fpToBE32(aff.x))
            data.append(contentsOf: fpToBE32(aff.y))
        } else {
            data.append(contentsOf: [UInt8](repeating: 0, count: 64))
        }
    }

    return Data(data)
}

private func importVKBinary(data: Data) -> Groth16VerificationKey? {
    let bytes = [UInt8](data)
    guard bytes.count >= 4 + 64 + 128 * 3 else { return nil }

    var offset = 0

    func readUInt32() -> UInt32 {
        let v = UInt32(bytes[offset]) | (UInt32(bytes[offset+1]) << 8) |
                (UInt32(bytes[offset+2]) << 16) | (UInt32(bytes[offset+3]) << 24)
        offset += 4
        return v
    }

    func readFp() -> Fp {
        let limbs = be32ToLimbs(Array(bytes[offset..<offset+32]))
        offset += 32
        let raw = Fp.from64(limbs)
        return fpMul(raw, Fp.from64(Fp.R2_MOD_P))
    }

    func readG1() -> PointProjective {
        let x = readFp()
        let y = readFp()
        return PointProjective(x: x, y: y, z: .one)
    }

    func readG2() -> G2ProjectivePoint {
        let xc0 = readFp()
        let xc1 = readFp()
        let yc0 = readFp()
        let yc1 = readFp()
        return G2ProjectivePoint(x: Fp2(c0: xc0, c1: xc1), y: Fp2(c0: yc0, c1: yc1), z: .one)
    }

    let nPublic = Int(readUInt32())
    let expectedSize = 4 + 64 + 128 * 3 + (nPublic + 1) * 64
    guard bytes.count >= expectedSize else { return nil }

    let alpha_g1 = readG1()
    let beta_g2 = readG2()
    let gamma_g2 = readG2()
    let delta_g2 = readG2()

    var ic = [PointProjective]()
    ic.reserveCapacity(nPublic + 1)
    for _ in 0...nPublic {
        ic.append(readG1())
    }

    return Groth16VerificationKey(
        alpha_g1: alpha_g1, beta_g2: beta_g2,
        gamma_g2: gamma_g2, delta_g2: delta_g2, ic: ic
    )
}

private func exportProofBinary(proof: Groth16Proof, publicInputs: [Fr]) -> Data? {
    guard let aAff = pointToAffine(proof.a),
          let bAff = g2ToAffine(proof.b),
          let cAff = pointToAffine(proof.c) else { return nil }

    var data = [UInt8]()
    // proof A (64 bytes), proof B (128 bytes), proof C (64 bytes), then inputs
    let totalSize = 64 + 128 + 64 + publicInputs.count * 32
    data.reserveCapacity(totalSize)

    // A
    data.append(contentsOf: fpToBE32(aAff.x))
    data.append(contentsOf: fpToBE32(aAff.y))

    // B
    data.append(contentsOf: fpToBE32(bAff.x.c0))
    data.append(contentsOf: fpToBE32(bAff.x.c1))
    data.append(contentsOf: fpToBE32(bAff.y.c0))
    data.append(contentsOf: fpToBE32(bAff.y.c1))

    // C
    data.append(contentsOf: fpToBE32(cAff.x))
    data.append(contentsOf: fpToBE32(cAff.y))

    // Public inputs
    for input in publicInputs {
        data.append(contentsOf: frToBE32(input))
    }

    return Data(data)
}

// MARK: - Hex/Binary Helpers

/// Convert Fp (Montgomery) to 32-byte big-endian representation.
private func fpToBE32(_ a: Fp) -> [UInt8] {
    let limbs = fpToInt(a)
    return limbsToBE32(limbs)
}

/// Convert Fr (Montgomery) to 32-byte big-endian representation.
private func frToBE32(_ a: Fr) -> [UInt8] {
    let limbs = frToInt(a)
    return limbsToBE32(limbs)
}

/// Convert 4 UInt64 limbs (little-endian) to 32-byte big-endian.
private func limbsToBE32(_ limbs: [UInt64]) -> [UInt8] {
    var bytes = [UInt8](repeating: 0, count: 32)
    for i in 0..<4 {
        let limb = limbs[i]
        let base = 24 - i * 8
        bytes[base + 0] = UInt8((limb >> 56) & 0xFF)
        bytes[base + 1] = UInt8((limb >> 48) & 0xFF)
        bytes[base + 2] = UInt8((limb >> 40) & 0xFF)
        bytes[base + 3] = UInt8((limb >> 32) & 0xFF)
        bytes[base + 4] = UInt8((limb >> 24) & 0xFF)
        bytes[base + 5] = UInt8((limb >> 16) & 0xFF)
        bytes[base + 6] = UInt8((limb >> 8) & 0xFF)
        bytes[base + 7] = UInt8(limb & 0xFF)
    }
    return bytes
}

/// Convert 32-byte big-endian to 4 UInt64 limbs (little-endian).
private func be32ToLimbs(_ bytes: [UInt8]) -> [UInt64] {
    var limbs = [UInt64](repeating: 0, count: 4)
    for i in 0..<4 {
        let base = 24 - i * 8
        limbs[i] = (UInt64(bytes[base]) << 56) | (UInt64(bytes[base + 1]) << 48) |
                   (UInt64(bytes[base + 2]) << 40) | (UInt64(bytes[base + 3]) << 32) |
                   (UInt64(bytes[base + 4]) << 24) | (UInt64(bytes[base + 5]) << 16) |
                   (UInt64(bytes[base + 6]) << 8) | UInt64(bytes[base + 7])
    }
    return limbs
}

/// Convert Fp to 64-char hex string (32-byte big-endian, no prefix).
private func fpToHex32(_ a: Fp) -> String {
    fpToBE32(a).map { String(format: "%02x", $0) }.joined()
}

/// Convert Fr to 64-char hex string (32-byte big-endian, no prefix).
private func frToHex32(_ a: Fr) -> String {
    frToBE32(a).map { String(format: "%02x", $0) }.joined()
}
